version: '3.8'
services:
  nginx-web1:
    image: nginxnew:latest
    container_name: nginx-web1
    ports:
      - "8001:80"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./web1/html:/usr/share/nginx/html
      - ./web1/nginx.conf:/etc/nginx/nginx.conf
    networks:
      web_net:
        ipv4_address: 192.168.10.2
    restart: always

  nginx-web2:
    image: nginxnew:latest
    container_name: nginx-web2
    ports:
      - "8002:80"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./web2/html:/usr/share/nginx/html
      - ./web2/nginx.conf:/etc/nginx/nginx.conf
    networks:
      web_net:
        ipv4_address: 192.168.10.3
    restart: always
networks:
  web_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
